
library(tidyverse)

gsw_head <- "src/gswteos-10.h"
gsw_head_text <- read_file(gsw_head)

functions_raw <- gsw_head_text %>%
  str_match_all(
    regex(
      "extern\\s+(double|int|void)\\s+(gsw_[a-zA-Z0-9_]+)\\(([^\\(]*)\\)\\s*;",
      multiline = TRUE
    )
  ) %>%
  .[[1]] %>%
  as.data.frame() %>%
  set_names(c("signature", "return_type", "name", "args")) %>%
  as_tibble()

args_raw <- functions_raw %>%
  select(return_type, name, args) %>%
  separate_rows(args, sep = "\\s*,") %>%
  extract(args, c("arg_type", "arg_name"), "([a-z_]+ ?\\*?)(.*?)\\s*$") %>%
  mutate(
    arg_name = str_trim(arg_name),
    arg_type = str_trim(arg_type) %>%
      str_replace("\\s*\\*", "*")
  ) %>%
  group_by(name) %>%
  mutate(arg_pos = 1:n()) %>%
  ungroup()

functions <- args_raw %>%
  group_by(name) %>%
  summarise(
    n_args = n(),
    return_type = return_type[1],
    arg_names = list(arg_name),
    arg_types = list(arg_type),
    signature = paste0(paste(arg_type, collapse = ", "), " => ", return_type[1])
  )

args <- args_raw %>%
  select(-return_type)


# generate wrapper functions
glue_c <- function(x, env = parent.frame()) {
  glue::glue(x, .envir = env, .open = "{{", .close = "}}")
}

type_info <- list(
  double = list(
    c_type = "double",
    vec_c_type = "REALSXP",
    vec_na = "NA_REAL",
    vec_is_na = "IS_NA",
    vec_ptr = "REAL"
  )
)

pointer_decl <- function(arg_names, arg_types) {
  arg_info <- transpose(lapply(arg_types, function(x) type_info[[x]]))
  glue_c("{{ arg_types }}* {{ arg_names }}_ptr = {{ arg_info$vec_ptr }}({{ arg_names }});") %>%
    paste0("    ", ., collapse = "\n")
}

fun_wrap_doubles_c <- function(name, return_type, arg_names, arg_types, ...) {
  glue_c(
"
SEXP teos10_c_{{ name }}_wrap({{ paste0('SEXP ', arg_names, collapse = ', ') }}) {
    R_xlen_t size = Rf_xlength({{ arg_names[1] }});
    SEXP out = PROTECT(Rf_allocVector(REALSXP, size));
    double* out_ptr = REAL(out);

{{ pointer_decl(arg_names, arg_types) }}

    for (R_xlen_t i = 0; i < size; i++) {
        out_ptr[i] = {{ name }}({{ paste0(arg_names, '_ptr[i]', collapse = ', ') }});
    }

    UNPROTECT(1);
    return out;
}
"
  ) %>% as.character()
}

fun_wrap_doubles_r <- function(name, arg_names, ...) {
  arg_indices <- seq_along(arg_names)
  glue_c(
    "
{{ name }} <- function({{ paste(arg_names, collapse = ', ')}}) {
  recycled <- recycle_common({{ paste(arg_names, collapse = ', ')}})
  .Call(teos10_c_{{ name }}_wrap, {{ paste0('recycled[[', arg_indices , ']]', collapse = ', ')}})
}
"
  ) %>% as.character()
}

impl_doubles <- functions %>%
  filter(
    return_type == "double",
    map_lgl(arg_types, ~all(. == "double"))
  ) %>%
  mutate(
    c_impl = pmap_chr(., fun_wrap_doubles_c),
    r_impl = pmap_chr(., fun_wrap_doubles_r)
  )

# write autogen files

unlink("src/teos10-wrappers.c")
glue_c(
'
// auto-generated by data-raw/wrap-teos-10.R. Do not modify by hand!
#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include "gswteos-10.h"

{{ paste(impl_doubles$c_impl, collapse = "\n\n") }}

'
) %>%
  write_file("src/teos10-wrappers.c")


unlink("r/teos10-wrappers.R")
glue_c(
  '
# auto-generated by data-raw/wrap-teos-10.R. Do not modify by hand!

{{ paste(impl_doubles$r_impl, collapse = "\n\n") }}

'
) %>%
  write_file("R/teos10-wrappers.R")
