#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
/* generated by data-raw/make-callentries.R */
extern SEXP teos10_c_gsw_alpha_wrap(SEXP sa, SEXP ct, SEXP p);
static const R_CallMethodDef CallEntries[] = {
    {"teos10_c_gsw_alpha_wrap", (DL_FUNC) &teos10_c_gsw_alpha_wrap, 3},
    {NULL, NULL, 0}
};
/* end generated by data-raw/make-callentries.R */

void R_init_teos10(DllInfo* dll){
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
