// auto-generated by data-raw/wrap-teos-10.R. Do not modify by hand!
#define R_NO_REMAP
#include <R.h>
#include <Rinternals.h>
#include "gswteos-10.h"

SEXP teos10_c_gsw_alpha_wrap(SEXP sa, SEXP ct, SEXP p) {
    R_xlen_t size = Rf_xlength(sa);
    SEXP out = PROTECT(Rf_allocVector(REALSXP, size));
    double* out_ptr = REAL(out);

    double* sa_ptr = REAL(sa);
    double* ct_ptr = REAL(ct);
    double* p_ptr = REAL(p);

    for (R_xlen_t i = 0; i < size; i++) {
        out_ptr[i] = gsw_alpha(sa_ptr[i], ct_ptr[i], p_ptr[i]);
    }

    UNPROTECT(1);
    return out;
}
