# auto-generated by data-raw/wrap-teos-10.R. Do not modify by hand!

gsw_adiabatic_lapse_rate_from_ct <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_adiabatic_lapse_rate_from_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_adiabatic_lapse_rate_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_adiabatic_lapse_rate_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_alpha <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_alpha_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_alpha_on_beta <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_alpha_on_beta_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_alpha_wrt_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_alpha_wrt_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_alpha_wrt_t_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_alpha_wrt_t_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_beta <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_beta_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_beta_const_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_beta_const_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_c_from_sp <- function(sp, t, p) {
  recycled <- recycle_common(sp, t, p)
  .Call(teos10_c_gsw_c_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_cabbeling <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_cabbeling_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_chem_potential_water_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_chem_potential_water_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_chem_potential_water_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_chem_potential_water_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_cp_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_cp_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_cp_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_cp_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_ct_freezing <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_ct_freezing_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_ct_freezing_poly <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_ct_freezing_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_ct_from_enthalpy <- function(sa, h, p) {
  recycled <- recycle_common(sa, h, p)
  .Call(teos10_c_gsw_ct_from_enthalpy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_ct_from_enthalpy_exact <- function(sa, h, p) {
  recycled <- recycle_common(sa, h, p)
  .Call(teos10_c_gsw_ct_from_enthalpy_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_ct_from_entropy <- function(sa, entropy) {
  recycled <- recycle_common(sa, entropy)
  .Call(teos10_c_gsw_ct_from_entropy_wrap, recycled[[1]], recycled[[2]])
}

gsw_ct_from_pt <- function(sa, pt) {
  recycled <- recycle_common(sa, pt)
  .Call(teos10_c_gsw_ct_from_pt_wrap, recycled[[1]], recycled[[2]])
}

gsw_ct_from_t <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_ct_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_ct_maxdensity <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_ct_maxdensity_wrap, recycled[[1]], recycled[[2]])
}

gsw_deltasa_atlas <- function(p, lon, lat) {
  recycled <- recycle_common(p, lon, lat)
  .Call(teos10_c_gsw_deltasa_atlas_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_deltasa_from_sp <- function(sp, p, lon, lat) {
  recycled <- recycle_common(sp, p, lon, lat)
  .Call(teos10_c_gsw_deltasa_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_dilution_coefficient_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_dilution_coefficient_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_dynamic_enthalpy <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_dynamic_enthalpy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_enthalpy <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_enthalpy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_enthalpy_ct_exact <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_enthalpy_ct_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_enthalpy_diff <- function(sa, ct, p_shallow, p_deep) {
  recycled <- recycle_common(sa, ct, p_shallow, p_deep)
  .Call(teos10_c_gsw_enthalpy_diff_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_enthalpy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_enthalpy_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_enthalpy_sso_0 <- function(p) {
  recycled <- recycle_common(p)
  .Call(teos10_c_gsw_enthalpy_sso_0_wrap, recycled[[1]])
}

gsw_enthalpy_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_enthalpy_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_entropy_from_ct <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_entropy_from_ct_wrap, recycled[[1]], recycled[[2]])
}

gsw_entropy_from_pt <- function(sa, pt) {
  recycled <- recycle_common(sa, pt)
  .Call(teos10_c_gsw_entropy_from_pt_wrap, recycled[[1]], recycled[[2]])
}

gsw_entropy_from_t <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_entropy_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_entropy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_entropy_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_entropy_part <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_entropy_part_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_entropy_part_zerop <- function(sa, pt0) {
  recycled <- recycle_common(sa, pt0)
  .Call(teos10_c_gsw_entropy_part_zerop_wrap, recycled[[1]], recycled[[2]])
}

gsw_fdelta <- function(p, lon, lat) {
  recycled <- recycle_common(p, lon, lat)
  .Call(teos10_c_gsw_fdelta_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_gibbs_ice_part_t <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_gibbs_ice_part_t_wrap, recycled[[1]], recycled[[2]])
}

gsw_gibbs_ice_pt0 <- function(pt0) {
  recycled <- recycle_common(pt0)
  .Call(teos10_c_gsw_gibbs_ice_pt0_wrap, recycled[[1]])
}

gsw_gibbs_ice_pt0_pt0 <- function(pt0) {
  recycled <- recycle_common(pt0)
  .Call(teos10_c_gsw_gibbs_ice_pt0_pt0_wrap, recycled[[1]])
}

gsw_gibbs_pt0_pt0 <- function(sa, pt0) {
  recycled <- recycle_common(sa, pt0)
  .Call(teos10_c_gsw_gibbs_pt0_pt0_wrap, recycled[[1]], recycled[[2]])
}

gsw_grav <- function(lat, p) {
  recycled <- recycle_common(lat, p)
  .Call(teos10_c_gsw_grav_wrap, recycled[[1]], recycled[[2]])
}

gsw_helmholtz_energy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_helmholtz_energy_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_hill_ratio_at_sp2 <- function(t) {
  recycled <- recycle_common(t)
  .Call(teos10_c_gsw_hill_ratio_at_sp2_wrap, recycled[[1]])
}

gsw_internal_energy <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_internal_energy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_internal_energy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_internal_energy_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_kappa <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_kappa_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_kappa_const_t_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_kappa_const_t_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_kappa_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_kappa_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_kappa_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_kappa_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_latentheat_evap_ct <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_latentheat_evap_ct_wrap, recycled[[1]], recycled[[2]])
}

gsw_latentheat_evap_t <- function(sa, t) {
  recycled <- recycle_common(sa, t)
  .Call(teos10_c_gsw_latentheat_evap_t_wrap, recycled[[1]], recycled[[2]])
}

gsw_latentheat_melting <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_latentheat_melting_wrap, recycled[[1]], recycled[[2]])
}

gsw_melting_ice_equilibrium_sa_ct_ratio <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_ice_equilibrium_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]])
}

gsw_melting_ice_equilibrium_sa_ct_ratio_poly <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_ice_equilibrium_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]])
}

gsw_melting_ice_sa_ct_ratio <- function(sa, ct, p, t_ih) {
  recycled <- recycle_common(sa, ct, p, t_ih)
  .Call(teos10_c_gsw_melting_ice_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_melting_ice_sa_ct_ratio_poly <- function(sa, ct, p, t_ih) {
  recycled <- recycle_common(sa, ct, p, t_ih)
  .Call(teos10_c_gsw_melting_ice_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_melting_seaice_equilibrium_sa_ct_ratio <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_seaice_equilibrium_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]])
}

gsw_melting_seaice_equilibrium_sa_ct_ratio_poly <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_seaice_equilibrium_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]])
}

gsw_melting_seaice_sa_ct_ratio <- function(sa, ct, p, sa_seaice, t_seaice) {
  recycled <- recycle_common(sa, ct, p, sa_seaice, t_seaice)
  .Call(teos10_c_gsw_melting_seaice_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]], recycled[[5]])
}

gsw_melting_seaice_sa_ct_ratio_poly <- function(sa, ct, p, sa_seaice, t_seaice) {
  recycled <- recycle_common(sa, ct, p, sa_seaice, t_seaice)
  .Call(teos10_c_gsw_melting_seaice_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]], recycled[[5]])
}

gsw_p_from_z <- function(z, lat) {
  recycled <- recycle_common(z, lat)
  .Call(teos10_c_gsw_p_from_z_wrap, recycled[[1]], recycled[[2]])
}

gsw_pot_enthalpy_from_pt_ice <- function(pt0_ice) {
  recycled <- recycle_common(pt0_ice)
  .Call(teos10_c_gsw_pot_enthalpy_from_pt_ice_wrap, recycled[[1]])
}

gsw_pot_enthalpy_from_pt_ice_poly <- function(pt0_ice) {
  recycled <- recycle_common(pt0_ice)
  .Call(teos10_c_gsw_pot_enthalpy_from_pt_ice_poly_wrap, recycled[[1]])
}

gsw_pot_enthalpy_ice_freezing <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_pot_enthalpy_ice_freezing_wrap, recycled[[1]], recycled[[2]])
}

gsw_pot_enthalpy_ice_freezing_poly <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_pot_enthalpy_ice_freezing_poly_wrap, recycled[[1]], recycled[[2]])
}

gsw_pot_rho_t_exact <- function(sa, t, p, p_ref) {
  recycled <- recycle_common(sa, t, p, p_ref)
  .Call(teos10_c_gsw_pot_rho_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_pressure_coefficient_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_pressure_coefficient_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_pressure_freezing_ct <- function(sa, ct, saturation_fraction) {
  recycled <- recycle_common(sa, ct, saturation_fraction)
  .Call(teos10_c_gsw_pressure_freezing_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_pt_from_ct <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_pt_from_ct_wrap, recycled[[1]], recycled[[2]])
}

gsw_pt_from_entropy <- function(sa, entropy) {
  recycled <- recycle_common(sa, entropy)
  .Call(teos10_c_gsw_pt_from_entropy_wrap, recycled[[1]], recycled[[2]])
}

gsw_pt_from_pot_enthalpy_ice <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt_from_pot_enthalpy_ice_wrap, recycled[[1]])
}

gsw_pt_from_pot_enthalpy_ice_poly <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt_from_pot_enthalpy_ice_poly_wrap, recycled[[1]])
}

gsw_pt_from_pot_enthalpy_ice_poly_dh <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt_from_pot_enthalpy_ice_poly_dh_wrap, recycled[[1]])
}

gsw_pt_from_t <- function(sa, t, p, p_ref) {
  recycled <- recycle_common(sa, t, p, p_ref)
  .Call(teos10_c_gsw_pt_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_pt_from_t_ice <- function(t, p, p_ref) {
  recycled <- recycle_common(t, p, p_ref)
  .Call(teos10_c_gsw_pt_from_t_ice_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_pt0_cold_ice_poly <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt0_cold_ice_poly_wrap, recycled[[1]])
}

gsw_pt0_from_t <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_pt0_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_pt0_from_t_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_pt0_from_t_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_rho <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_rho_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_rho_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_rho_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_rho_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_rho_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sa_freezing_from_ct <- function(ct, p, saturation_fraction) {
  recycled <- recycle_common(ct, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sa_freezing_from_ct_poly <- function(ct, p, saturation_fraction) {
  recycled <- recycle_common(ct, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_ct_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sa_freezing_from_t <- function(t, p, saturation_fraction) {
  recycled <- recycle_common(t, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sa_freezing_from_t_poly <- function(t, p, saturation_fraction) {
  recycled <- recycle_common(t, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_t_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sa_from_rho <- function(rho, ct, p) {
  recycled <- recycle_common(rho, ct, p)
  .Call(teos10_c_gsw_sa_from_rho_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sa_from_sp <- function(sp, p, lon, lat) {
  recycled <- recycle_common(sp, p, lon, lat)
  .Call(teos10_c_gsw_sa_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_sa_from_sp_baltic <- function(sp, lon, lat) {
  recycled <- recycle_common(sp, lon, lat)
  .Call(teos10_c_gsw_sa_from_sp_baltic_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sa_from_sstar <- function(sstar, p, lon, lat) {
  recycled <- recycle_common(sstar, p, lon, lat)
  .Call(teos10_c_gsw_sa_from_sstar_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_saar <- function(p, lon, lat) {
  recycled <- recycle_common(p, lon, lat)
  .Call(teos10_c_gsw_saar_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sigma0 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma0_wrap, recycled[[1]], recycled[[2]])
}

gsw_sigma1 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma1_wrap, recycled[[1]], recycled[[2]])
}

gsw_sigma2 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma2_wrap, recycled[[1]], recycled[[2]])
}

gsw_sigma3 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma3_wrap, recycled[[1]], recycled[[2]])
}

gsw_sigma4 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma4_wrap, recycled[[1]], recycled[[2]])
}

gsw_sound_speed <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_sound_speed_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sound_speed_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_sound_speed_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_sound_speed_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_sound_speed_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sp_from_c <- function(c, t, p) {
  recycled <- recycle_common(c, t, p)
  .Call(teos10_c_gsw_sp_from_c_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sp_from_sa <- function(sa, p, lon, lat) {
  recycled <- recycle_common(sa, p, lon, lat)
  .Call(teos10_c_gsw_sp_from_sa_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_sp_from_sa_baltic <- function(sa, lon, lat) {
  recycled <- recycle_common(sa, lon, lat)
  .Call(teos10_c_gsw_sp_from_sa_baltic_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_sp_from_sk <- function(sk) {
  recycled <- recycle_common(sk)
  .Call(teos10_c_gsw_sp_from_sk_wrap, recycled[[1]])
}

gsw_sp_from_sr <- function(sr) {
  recycled <- recycle_common(sr)
  .Call(teos10_c_gsw_sp_from_sr_wrap, recycled[[1]])
}

gsw_sp_from_sstar <- function(sstar, p, lon, lat) {
  recycled <- recycle_common(sstar, p, lon, lat)
  .Call(teos10_c_gsw_sp_from_sstar_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_specvol <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_specvol_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_specvol_anom_standard <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_specvol_anom_standard_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_specvol_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_specvol_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_specvol_sso_0 <- function(p) {
  recycled <- recycle_common(p)
  .Call(teos10_c_gsw_specvol_sso_0_wrap, recycled[[1]])
}

gsw_specvol_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_specvol_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_spiciness0 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_spiciness0_wrap, recycled[[1]], recycled[[2]])
}

gsw_spiciness1 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_spiciness1_wrap, recycled[[1]], recycled[[2]])
}

gsw_spiciness2 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_spiciness2_wrap, recycled[[1]], recycled[[2]])
}

gsw_sr_from_sp <- function(sp) {
  recycled <- recycle_common(sp)
  .Call(teos10_c_gsw_sr_from_sp_wrap, recycled[[1]])
}

gsw_sstar_from_sa <- function(sa, p, lon, lat) {
  recycled <- recycle_common(sa, p, lon, lat)
  .Call(teos10_c_gsw_sstar_from_sa_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_sstar_from_sp <- function(sp, p, lon, lat) {
  recycled <- recycle_common(sp, p, lon, lat)
  .Call(teos10_c_gsw_sstar_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

gsw_t_deriv_chem_potential_water_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_t_deriv_chem_potential_water_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_t_freezing <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_t_freezing_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_t_freezing_poly <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_t_freezing_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_t_from_ct <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_t_from_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_t_from_pt0_ice <- function(pt0_ice, p) {
  recycled <- recycle_common(pt0_ice, p)
  .Call(teos10_c_gsw_t_from_pt0_ice_wrap, recycled[[1]], recycled[[2]])
}

gsw_thermobaric <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_thermobaric_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

gsw_z_from_p <- function(p, lat) {
  recycled <- recycle_common(p, lat)
  .Call(teos10_c_gsw_z_from_p_wrap, recycled[[1]], recycled[[2]])
}
