# auto-generated by data-raw/wrap-teos-10.R. Do not modify by hand!

gsw_alpha <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_alpha_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}
