# auto-generated by data-raw/wrap-teos-10.R. Do not modify by hand!

#' gsw_adiabatic_lapse_rate_from_ct
#'
#' Calculates the adiabatic lapse rate from Conservative Temperature
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_adiabatic_lapse_rate_from_ct()`](http://www.teos-10.org/pubs/gsw/html/gsw_adiabatic_lapse_rate_from_ct.html)
#'
#' @export
gsw_adiabatic_lapse_rate_from_ct <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_adiabatic_lapse_rate_from_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_adiabatic_lapse_rate_ice
#'
#' Calculates the adiabatic lapse rate of ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_adiabatic_lapse_rate_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_adiabatic_lapse_rate_ice.html)
#'
#' @export
gsw_adiabatic_lapse_rate_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_adiabatic_lapse_rate_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_alpha
#'
#' Calculates the thermal expansion coefficient of seawater with respect to 
#' Conservative Temperature using the computationally-efficient 48-term 
#' expression for density in terms of SA, CT and p (IOC et al., 2010)
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_alpha()`](http://www.teos-10.org/pubs/gsw/html/gsw_alpha.html)
#'
#' @export
gsw_alpha <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_alpha_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_alpha_on_beta
#'
#' Calculates alpha divided by beta, where alpha is the thermal expansion
#' coefficient and beta is the saline contraction coefficient of seawater 
#' from Absolute Salinity and Conservative Temperature.  This function uses
#' the computationally-efficient expression for specific volume in terms of 
#' SA, CT and p (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_alpha_on_beta()`](http://www.teos-10.org/pubs/gsw/html/gsw_alpha_on_beta.html)
#'
#' @export
gsw_alpha_on_beta <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_alpha_on_beta_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_alpha_wrt_t_exact
#'
#' Calculates thermal expansion coefficient of seawater with respect to 
#' in-situ temperature
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_alpha_wrt_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_alpha_wrt_t_exact.html)
#'
#' @export
gsw_alpha_wrt_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_alpha_wrt_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_alpha_wrt_t_ice
#'
#' Calculates the thermal expansion coefficient of ice with respect to  
#' in-situ temperature.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_alpha_wrt_t_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_alpha_wrt_t_ice.html)
#'
#' @export
gsw_alpha_wrt_t_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_alpha_wrt_t_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_beta
#'
#' Calculates the saline (i.e. haline) contraction coefficient of seawater  
#' at constant Conservative Temperature using the computationally-efficient
#' expression for specific volume in terms of SA, CT and p 
#' (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_beta()`](http://www.teos-10.org/pubs/gsw/html/gsw_beta.html)
#'
#' @export
gsw_beta <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_beta_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_beta_const_t_exact
#'
#' Calculates saline (haline) contraction coefficient of seawater at 
#' constant in-situ temperature.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_beta_const_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_beta_const_t_exact.html)
#'
#' @export
gsw_beta_const_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_beta_const_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_c_from_sp
#'
#' Calculates conductivity, C, from (SP,t,p) using PSS-78 in the range
#' 2 < SP < 42.  If the input Practical Salinity is less than 2 then a
#' modified form of the Hill et al. (1986) fomula is used for Practical
#' Salinity.  The modification of the Hill et al. (1986) expression is to
#' ensure that it is exactly consistent with PSS-78 at SP = 2.
#' The conductivity ratio returned by this function is consistent with the
#' input value of Practical Salinity, SP, to 2x10^-14 psu over the full
#' range of input parameters (from pure fresh water up to SP = 42 psu).
#' This error of 2x10^-14 psu is machine precision at typical seawater
#' salinities.  This accuracy is achieved by having four different
#' polynomials for the starting value of Rtx (the square root of Rt) in
#' four different ranges of SP, and by using one and a half iterations of
#' a computationally efficient modified Newton-Raphson technique (McDougall
#' and Wotherspoon, 2012) to find the root of the equation.
#' Note that strictly speaking PSS-78 (Unesco, 1983) defines Practical
#' Salinity in terms of the conductivity ratio, R, without actually
#' specifying the value of C(35,15,0) (which we currently take to be
#' 42.9140 mS/cm).
#'
#' @param sp Practical Salinity `[ unitless ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_c_from_sp()`](http://www.teos-10.org/pubs/gsw/html/gsw_c_from_sp.html)
#'
#' @export
gsw_c_from_sp <- function(sp, t, p) {
  recycled <- recycle_common(sp, t, p)
  .Call(teos10_c_gsw_c_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_cabbeling
#'
#' Calculates the cabbeling coefficient of seawater with respect to  
#' Conservative Temperature.  This function uses the computationally-
#' efficient expression for specific volume in terms of SA, CT and p
#' (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_cabbeling()`](http://www.teos-10.org/pubs/gsw/html/gsw_cabbeling.html)
#'
#' @export
gsw_cabbeling <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_cabbeling_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_chem_potential_water_ice
#'
#' Calculates the chemical potential of water in ice from in-situ
#' temperature and pressure.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_chem_potential_water_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_chem_potential_water_ice.html)
#'
#' @export
gsw_chem_potential_water_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_chem_potential_water_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_chem_potential_water_t_exact
#'
#' Calculates the chemical potential of water in seawater.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_chem_potential_water_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_chem_potential_water_t_exact.html)
#'
#' @export
gsw_chem_potential_water_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_chem_potential_water_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_cp_ice
#'
#' Calculates the isobaric heat capacity of seawater.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_cp_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_cp_ice.html)
#'
#' @export
gsw_cp_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_cp_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_cp_t_exact
#'
#' Calculates isobaric heat capacity of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_cp_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_cp_t_exact.html)
#'
#' @export
gsw_cp_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_cp_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_ct_freezing
#'
#' Calculates the Conservative Temperature at which seawater freezes.  The
#' Conservative Temperature freezing point is calculated from the exact
#' in-situ freezing temperature which is found by a modified Newton-Raphson
#' iteration (McDougall and Wotherspoon, 2013) of the equality of the
#' chemical potentials of water in seawater and in ice.
#' An alternative GSW function, gsw_CT_freezing_poly, it is based on a
#' computationally-efficient polynomial, and is accurate to within -5e-4 K
#' and 6e-4 K, when compared with this function.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_freezing()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_freezing.html)
#'
#' @export
gsw_ct_freezing <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_ct_freezing_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_ct_freezing_poly
#'
#' Calculates the Conservative Temperature at which seawater freezes.
#' The error of this fit ranges between -5e-4 K and 6e-4 K when compared 
#' with the Conservative Temperature calculated from the exact in-situ 
#' freezing temperature which is found by a Newton-Raphson iteration of the 
#' equality of the chemical potentials of water in seawater and in ice.  
#' Note that the Conservative temperature freezing temperature can be found
#' by this exact method using the function gsw_CT_freezing.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_freezing_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_freezing_poly.html)
#'
#' @export
gsw_ct_freezing_poly <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_ct_freezing_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_ct_from_enthalpy
#'
#' Calculates the Conservative Temperature of seawater, given the Absolute 
#' Salinity, specific enthalpy, h, and pressure p.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param h specific enthalpy `[ J/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_from_enthalpy()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_from_enthalpy.html)
#'
#' @export
gsw_ct_from_enthalpy <- function(sa, h, p) {
  recycled <- recycle_common(sa, h, p)
  .Call(teos10_c_gsw_ct_from_enthalpy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_ct_from_enthalpy_exact
#'
#' Calculates the Conservative Temperature of seawater, given the Absolute 
#' Salinity, specific enthalpy, h, and pressure p.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param h specific enthalpy `[ J/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_from_enthalpy_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_from_enthalpy_exact.html)
#'
#' @export
gsw_ct_from_enthalpy_exact <- function(sa, h, p) {
  recycled <- recycle_common(sa, h, p)
  .Call(teos10_c_gsw_ct_from_enthalpy_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_ct_from_entropy
#'
#' Calculates Conservative Temperature with entropy as an input variable.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param entropy specific entropy `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_from_entropy()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_from_entropy.html)
#'
#' @export
gsw_ct_from_entropy <- function(sa, entropy) {
  recycled <- recycle_common(sa, entropy)
  .Call(teos10_c_gsw_ct_from_entropy_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_ct_from_pt
#'
#' Calculates Conservative Temperature from potential temperature of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param pt potential temperature with reference pressure of 0 dbar `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_from_pt()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_from_pt.html)
#'
#' @export
gsw_ct_from_pt <- function(sa, pt) {
  recycled <- recycle_common(sa, pt)
  .Call(teos10_c_gsw_ct_from_pt_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_ct_from_t
#'
#' Calculates Conservative Temperature from in-situ temperature
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_from_t()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_from_t.html)
#'
#' @export
gsw_ct_from_t <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_ct_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_ct_maxdensity
#'
#' Calculates the Conservative Temperature of maximum density of seawater. 
#' This function returns the Conservative temperature at which the density
#' of seawater is a maximum, at given Absolute Salinity, SA, and sea 
#' pressure, p (in dbar).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_ct_maxdensity()`](http://www.teos-10.org/pubs/gsw/html/gsw_ct_maxdensity.html)
#'
#' @export
gsw_ct_maxdensity <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_ct_maxdensity_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_deltasa_atlas
#'
#' Calculates the Absolute Salinity Anomaly atlas value, delta_SA_atlas.
#'
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_deltasa_atlas()`](http://www.teos-10.org/pubs/gsw/html/gsw_deltasa_atlas.html)
#'
#' @export
gsw_deltasa_atlas <- function(p, lon, lat) {
  recycled <- recycle_common(p, lon, lat)
  .Call(teos10_c_gsw_deltasa_atlas_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_deltasa_from_sp
#'
#' Calculates Absolute Salinity Anomaly, deltaSA, from Practical Salinity, SP.
#'
#' @param sp Practical Salinity `[ unitless ]`
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_deltasa_from_sp()`](http://www.teos-10.org/pubs/gsw/html/gsw_deltasa_from_sp.html)
#'
#' @export
gsw_deltasa_from_sp <- function(sp, p, lon, lat) {
  recycled <- recycle_common(sp, p, lon, lat)
  .Call(teos10_c_gsw_deltasa_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_dilution_coefficient_t_exact
#'
#' Calculates the dilution coefficient of seawater.  The dilution 
#' coefficient of seawater is defined as the Absolute Salinity times the 
#' second derivative of the Gibbs function with respect to Absolute 
#' Salinity, that is, SA.*g_SA_SA.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_dilution_coefficient_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_dilution_coefficient_t_exact.html)
#'
#' @export
gsw_dilution_coefficient_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_dilution_coefficient_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_dynamic_enthalpy
#'
#' Calculates dynamic enthalpy of seawater using the computationally-
#' efficient expression for specific volume in terms of SA, CT and p
#' (Roquet et al., 2014).  Dynamic enthalpy is defined as enthalpy minus
#' |  potential enthalpy (Young, 2010).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_dynamic_enthalpy()`](http://www.teos-10.org/pubs/gsw/html/gsw_dynamic_enthalpy.html)
#'
#' @export
gsw_dynamic_enthalpy <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_dynamic_enthalpy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_enthalpy
#'
#' Calculates specific enthalpy of seawater using the computationally-
#' efficient expression for specific volume in terms of SA, CT and p
#' (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_enthalpy()`](http://www.teos-10.org/pubs/gsw/html/gsw_enthalpy.html)
#'
#' @export
gsw_enthalpy <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_enthalpy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_enthalpy_ct_exact
#'
#' Calculates specific enthalpy of seawater from Absolute Salinity and 
#' Conservative Temperature and pressure.  
#' Note that this function uses the full Gibbs function.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_enthalpy_ct_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_enthalpy_ct_exact.html)
#'
#' @export
gsw_enthalpy_ct_exact <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_enthalpy_ct_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_enthalpy_diff
#'
#' Calculates the difference of the specific enthalpy of seawater between 
#' two different pressures, p_deep (the deeper pressure) and p_shallow
#' (the shallower pressure), at the same values of SA and CT.  This 
#' function uses the computationally-efficient expression for specific 
#' volume in terms of SA, CT and p (Roquet et al., 2014).  The output
#' (enthalpy_diff_CT) is the specific enthalpy evaluated at (SA,CT,p_deep)
#' minus the specific enthalpy at (SA,CT,p_shallow).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p_shallow upper sea pressure (i.e. shallower absolute pressure - 10.1325 dbar) `[ dbar ]`
#' @param p_deep lower sea pressure (i.e. deeper absolute pressure - 10.1325 dbar) `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_enthalpy_diff()`](http://www.teos-10.org/pubs/gsw/html/gsw_enthalpy_diff.html)
#'
#' @export
gsw_enthalpy_diff <- function(sa, ct, p_shallow, p_deep) {
  recycled <- recycle_common(sa, ct, p_shallow, p_deep)
  .Call(teos10_c_gsw_enthalpy_diff_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_enthalpy_ice
#'
#' Calculates the specific enthalpy of ice (h_Ih).
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_enthalpy_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_enthalpy_ice.html)
#'
#' @export
gsw_enthalpy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_enthalpy_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_enthalpy_sso_0
#'
#' This function calculates enthalpy at the Standard Ocean Salinity, SSO,
#' and at a Conservative Temperature of zero degrees C, as a function of
#' pressure, p, in dbar, using a streamlined version of the
#' computationally-efficient expression for specific volume, that is, a
#' streamlined version of the code "gsw_enthalpy(SA,CT,p)".
#'
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_enthalpy_sso_0()`](http://www.teos-10.org/pubs/gsw/html/gsw_enthalpy_sso_0.html)
#'
#' @export
gsw_enthalpy_sso_0 <- function(p) {
  recycled <- recycle_common(p)
  .Call(teos10_c_gsw_enthalpy_sso_0_wrap, recycled[[1]])
}

#' gsw_enthalpy_t_exact
#'
#' Calculates the specific enthalpy of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_enthalpy_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_enthalpy_t_exact.html)
#'
#' @export
gsw_enthalpy_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_enthalpy_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_entropy_from_ct
#'
#' Calculates specific entropy of seawater from Conservative Temperature.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_entropy_from_ct()`](http://www.teos-10.org/pubs/gsw/html/gsw_entropy_from_ct.html)
#'
#' @export
gsw_entropy_from_ct <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_entropy_from_ct_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_entropy_from_pt
#'
#' Calculates specific entropy of seawater.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param pt potential temperature with reference pressure of 0 dbar `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_entropy_from_pt()`](http://www.teos-10.org/pubs/gsw/html/gsw_entropy_from_pt.html)
#'
#' @export
gsw_entropy_from_pt <- function(sa, pt) {
  recycled <- recycle_common(sa, pt)
  .Call(teos10_c_gsw_entropy_from_pt_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_entropy_from_t
#'
#' Calculates the specific entropy of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_entropy_from_t()`](http://www.teos-10.org/pubs/gsw/html/gsw_entropy_from_t.html)
#'
#' @export
gsw_entropy_from_t <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_entropy_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_entropy_ice
#'
#' Calculates specific entropy of ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_entropy_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_entropy_ice.html)
#'
#' @export
gsw_entropy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_entropy_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_entropy_part
#'
#' entropy minus the terms that are a function of only SA
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_entropy_part()`](http://www.teos-10.org/pubs/gsw/html/gsw_entropy_part.html)
#'
#' @export
gsw_entropy_part <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_entropy_part_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_entropy_part_zerop
#'
#' entropy part evaluated at the sea surface
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param pt0 insitu temperature `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_entropy_part_zerop()`](http://www.teos-10.org/pubs/gsw/html/gsw_entropy_part_zerop.html)
#'
#' @export
gsw_entropy_part_zerop <- function(sa, pt0) {
  recycled <- recycle_common(sa, pt0)
  .Call(teos10_c_gsw_entropy_part_zerop_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_fdelta
#'
#' Calculates fdelta.
#'
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_fdelta()`](http://www.teos-10.org/pubs/gsw/html/gsw_fdelta.html)
#'
#' @export
gsw_fdelta <- function(p, lon, lat) {
  recycled <- recycle_common(p, lon, lat)
  .Call(teos10_c_gsw_fdelta_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_gibbs_ice_part_t
#'
#' part of the the first temperature derivative of Gibbs energy of ice
#' that is the outout is gibbs_ice(1,0,t,p) + S0
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_gibbs_ice_part_t()`](http://www.teos-10.org/pubs/gsw/html/gsw_gibbs_ice_part_t.html)
#'
#' @export
gsw_gibbs_ice_part_t <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_gibbs_ice_part_t_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_gibbs_ice_pt0
#'
#' Part of the the first temperature derivative of Gibbs energy of ice
#' that is the outout is "gibbs_ice(1,0,pt0,0) + s0"
#'
#' @param pt0 insitu temperature `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_gibbs_ice_pt0()`](http://www.teos-10.org/pubs/gsw/html/gsw_gibbs_ice_pt0.html)
#'
#' @export
gsw_gibbs_ice_pt0 <- function(pt0) {
  recycled <- recycle_common(pt0)
  .Call(teos10_c_gsw_gibbs_ice_pt0_wrap, recycled[[1]])
}

#' gsw_gibbs_ice_pt0_pt0
#'
#' The second temperature derivative of Gibbs energy of ice at the 
#' potential temperature with reference sea pressure of zero dbar.  That is
#' the output is gibbs_ice(2,0,pt0,0).
#'
#' @param pt0 insitu temperature `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_gibbs_ice_pt0_pt0()`](http://www.teos-10.org/pubs/gsw/html/gsw_gibbs_ice_pt0_pt0.html)
#'
#' @export
gsw_gibbs_ice_pt0_pt0 <- function(pt0) {
  recycled <- recycle_common(pt0)
  .Call(teos10_c_gsw_gibbs_ice_pt0_pt0_wrap, recycled[[1]])
}

#' gsw_gibbs_pt0_pt0
#'
#' gibbs_tt at (sa,pt,0)
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param pt0 insitu temperature `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_gibbs_pt0_pt0()`](http://www.teos-10.org/pubs/gsw/html/gsw_gibbs_pt0_pt0.html)
#'
#' @export
gsw_gibbs_pt0_pt0 <- function(sa, pt0) {
  recycled <- recycle_common(sa, pt0)
  .Call(teos10_c_gsw_gibbs_pt0_pt0_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_grav
#'
#' Calculates acceleration due to gravity as a function of latitude and as
#' a function of pressure in the ocean.
#'
#' @param lat latitude `[ deg N ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_grav()`](http://www.teos-10.org/pubs/gsw/html/gsw_grav.html)
#'
#' @export
gsw_grav <- function(lat, p) {
  recycled <- recycle_common(lat, p)
  .Call(teos10_c_gsw_grav_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_helmholtz_energy_ice
#'
#' Calculates the Helmholtz energy of ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_helmholtz_energy_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_helmholtz_energy_ice.html)
#'
#' @export
gsw_helmholtz_energy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_helmholtz_energy_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_hill_ratio_at_sp2
#'
#' Calculates the Hill ratio, which is the adjustment needed to apply for
#' Practical Salinities smaller than 2.  This ratio is defined at a 
#' Practical Salinity = 2 and in-situ temperature, t using PSS-78. The Hill
#' ratio is the ratio of 2 to the output of the Hill et al. (1986) formula
#' for Practical Salinity at the conductivity ratio, Rt, at which Practical
#' Salinity on the PSS-78 scale is exactly 2.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_hill_ratio_at_sp2()`](http://www.teos-10.org/pubs/gsw/html/gsw_hill_ratio_at_sp2.html)
#'
#' @export
gsw_hill_ratio_at_sp2 <- function(t) {
  recycled <- recycle_common(t)
  .Call(teos10_c_gsw_hill_ratio_at_sp2_wrap, recycled[[1]])
}

#' gsw_internal_energy
#'
#' Calculates internal energy of seawater.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_internal_energy()`](http://www.teos-10.org/pubs/gsw/html/gsw_internal_energy.html)
#'
#' @export
gsw_internal_energy <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_internal_energy_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_internal_energy_ice
#'
#' Calculates the specific internal energy of ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_internal_energy_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_internal_energy_ice.html)
#'
#' @export
gsw_internal_energy_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_internal_energy_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_kappa
#'
#' Calculates isentropic compressibility of seawater.  This function
#' has inputs of Absolute Salinity and Conservative Temperature.  This
#' function uses the computationally-efficient expression for
#' specific volume in terms of SA, CT and p (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_kappa()`](http://www.teos-10.org/pubs/gsw/html/gsw_kappa.html)
#'
#' @export
gsw_kappa <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_kappa_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_kappa_const_t_ice
#'
#' Calculates isothermal compressibility of ice. 
#' Note. This is the compressibility of ice AT CONSTANT IN-SITU
#' TEMPERATURE
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_kappa_const_t_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_kappa_const_t_ice.html)
#'
#' @export
gsw_kappa_const_t_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_kappa_const_t_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_kappa_ice
#'
#' Calculates the isentropic compressibility of ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_kappa_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_kappa_ice.html)
#'
#' @export
gsw_kappa_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_kappa_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_kappa_t_exact
#'
#' isentropic compressibility of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_kappa_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_kappa_t_exact.html)
#'
#' @export
gsw_kappa_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_kappa_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_latentheat_evap_ct
#'
#' Calculates latent heat, or enthalpy, of evaporation.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_latentheat_evap_ct()`](http://www.teos-10.org/pubs/gsw/html/gsw_latentheat_evap_ct.html)
#'
#' @export
gsw_latentheat_evap_ct <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_latentheat_evap_ct_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_latentheat_evap_t
#'
#' Calculates latent heat, or enthalpy, of evaporation.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_latentheat_evap_t()`](http://www.teos-10.org/pubs/gsw/html/gsw_latentheat_evap_t.html)
#'
#' @export
gsw_latentheat_evap_t <- function(sa, t) {
  recycled <- recycle_common(sa, t)
  .Call(teos10_c_gsw_latentheat_evap_t_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_latentheat_melting
#'
#' Calculates latent heat, or enthalpy, of melting.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_latentheat_melting()`](http://www.teos-10.org/pubs/gsw/html/gsw_latentheat_melting.html)
#'
#' @export
gsw_latentheat_melting <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_latentheat_melting_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_melting_ice_equilibrium_sa_ct_ratio
#'
#' Calculates the ratio of SA to CT changes when ice melts into seawater
#' with both the seawater and the seaice temperatures being almost equal to
#' the equilibrium freezing temperature.  It is assumed that a small mass 
#' of ice melts into an infinite mass of seawater.  If indeed the 
#' temperature of the seawater and the ice were both equal to the freezing
#' temperature, then no melting or freezing would occur an imbalance 
#' between these three temperatures is needed for freezing or melting to
#' occur (the three temperatures being (1) the seawater temperature, 
#' (2) the ice temperature, and (3) the freezing temperature.  
#' The output, melting_ice_equilibrium_SA_CT_ratio, is dSA/dCT rather than 
#' dCT/dSA.  This is done so that when SA = 0, the output, dSA/dCT is zero
#' whereas dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_ice_equilibrium_sa_ct_ratio()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_ice_equilibrium_sa_ct_ratio.html)
#'
#' @export
gsw_melting_ice_equilibrium_sa_ct_ratio <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_ice_equilibrium_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_melting_ice_equilibrium_sa_ct_ratio_poly
#'
#' Calculates the ratio of SA to CT changes when ice melts into seawater
#' with both the seawater and the seaice temperatures being almost equal to
#' the equilibrium freezing temperature.  It is assumed that a small mass
#' of ice melts into an infinite mass of seawater.  If indeed the
#' temperature of the seawater and the ice were both equal to the freezing
#' temperature, then no melting or freezing would occur an imbalance
#' between these three temperatures is needed for freezing or melting to
#' occur (the three temperatures being (1) the seawater temperature,
#' (2) the ice temperature, and (3) the freezing temperature.
#' The output, melting_ice_equilibrium_SA_CT_ratio, is dSA/dCT rather than
#' dCT/dSA.  This is done so that when SA = 0, the output, dSA/dCT is zero
#' whereas dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_ice_equilibrium_sa_ct_ratio_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_ice_equilibrium_sa_ct_ratio_poly.html)
#'
#' @export
gsw_melting_ice_equilibrium_sa_ct_ratio_poly <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_ice_equilibrium_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_melting_ice_sa_ct_ratio
#'
#' Calculates the ratio of SA to CT changes when ice melts into seawater.
#' It is assumed that a small mass of ice melts into an infinite mass of
#' seawater.  Because of the infinite mass of seawater, the ice will always
#' melt.   
#' The output, melting_seaice_SA_CT_ratio, is dSA/dCT rather than dCT/dSA. 
#' This is done so that when SA = 0, the output, dSA/dCT is zero whereas 
#' dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#' @param t_ih in-situ temperature of the ice at pressure p (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_ice_sa_ct_ratio()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_ice_sa_ct_ratio.html)
#'
#' @export
gsw_melting_ice_sa_ct_ratio <- function(sa, ct, p, t_ih) {
  recycled <- recycle_common(sa, ct, p, t_ih)
  .Call(teos10_c_gsw_melting_ice_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_melting_ice_sa_ct_ratio_poly
#'
#' Calculates the ratio of SA to CT changes when ice melts into seawater.
#' It is assumed that a small mass of ice melts into an infinite mass of
#' seawater.  Because of the infinite mass of seawater, the ice will always
#' melt.
#' The output, melting_seaice_SA_CT_ratio, is dSA/dCT rather than dCT/dSA.
#' This is done so that when SA = 0, the output, dSA/dCT is zero whereas
#' dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#' @param t_ih in-situ temperature of the ice at pressure p (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_ice_sa_ct_ratio_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_ice_sa_ct_ratio_poly.html)
#'
#' @export
gsw_melting_ice_sa_ct_ratio_poly <- function(sa, ct, p, t_ih) {
  recycled <- recycle_common(sa, ct, p, t_ih)
  .Call(teos10_c_gsw_melting_ice_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_melting_seaice_equilibrium_sa_ct_ratio
#'
#' Calculates the ratio of SA to CT changes when sea ice melts into 
#' seawater with both the seawater and the sea ice temperatures being  
#' almost equal to the equilibrium freezing temperature.  It is assumed  
#' that a small mass of seaice melts into an infinite mass of seawater.  If 
#' indeed the temperature of the seawater and the sea ice were both equal  
#' to the freezing temperature, then no melting or freezing would occur; an  
#' imbalance between these three temperatures is needed for freezing or 
#' melting to occur (the three temperatures being (1) the seawater 
#' temperature, (2) the sea ice temperature, and (3) the freezing 
#' temperature.  
#' Note that the output of this function, dSA/dCT is independent of the 
#' sea ice salinity, SA_seaice.  That is, the output applies equally to  
#' pure ice Ih and to sea ice with seaice salinity, SA_seaice.  This result 
#' is proven in the manuscript, McDougall et al. (2013).  
#' The output, melting_seaice_equilibrium_SA_CT_ratio, is dSA/dCT rather  
#' than dCT/dSA.  This is done so that when SA = 0, the output, dSA/dCT is 
#' zero whereas dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_seaice_equilibrium_sa_ct_ratio()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_seaice_equilibrium_sa_ct_ratio.html)
#'
#' @export
gsw_melting_seaice_equilibrium_sa_ct_ratio <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_seaice_equilibrium_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_melting_seaice_equilibrium_sa_ct_ratio_poly
#'
#' Calculates the ratio of SA to CT changes when sea ice melts into
#' seawater with both the seawater and the sea ice temperatures being
#' almost equal to the equilibrium freezing temperature.  It is assumed
#' that a small mass of seaice melts into an infinite mass of seawater.  If
#' indeed the temperature of the seawater and the sea ice were both equal
#' to the freezing temperature, then no melting or freezing would occur; an
#' imbalance between these three temperatures is needed for freezing or
#' melting to occur (the three temperatures being (1) the seawater
#' temperature, (2) the sea ice temperature, and (3) the freezing
#' temperature.
#' Note that the output of this function, dSA/dCT is independent of the
#' sea ice salinity, SA_seaice.  That is, the output applies equally to
#' pure ice Ih and to sea ice with seaice salinity, SA_seaice.  This result
#' is proven in the manuscript, McDougall et al. (2013).
#' The output, melting_seaice_equilibrium_SA_CT_ratio, is dSA/dCT rather
#' than dCT/dSA.  This is done so that when SA = 0, the output, dSA/dCT is
#' zero whereas dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_seaice_equilibrium_sa_ct_ratio_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_seaice_equilibrium_sa_ct_ratio_poly.html)
#'
#' @export
gsw_melting_seaice_equilibrium_sa_ct_ratio_poly <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_melting_seaice_equilibrium_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_melting_seaice_sa_ct_ratio
#'
#' Calculates the ratio of SA to CT changes when sea ice melts into seawater.
#' It is assumed that a small mass of sea ice melts into an infinite mass of
#' seawater.  Because of the infinite mass of seawater, the sea ice will 
#' always melt.   
#' Ice formed at the sea surface (sea ice) typically contains between 2 g/kg
#' and 12 g/kg of salt (defined as the mass of salt divided by the mass of 
#' ice Ih plus brine) and this programme returns NaN's if the input 
#' SA_seaice is greater than 15 g/kg.  If the SA_seaice input is not zero, 
#' usually this would imply that the pressure p should be zero, as sea ice 
#' only occurs near the sea surface.  The code does not impose that p = 0 if 
#' SA_seaice is non-zero.  Rather, this is left to the user.  
#' The Absolute Salinity, SA_brine, of the brine trapped in little pockets 
#' in the sea ice, is in thermodynamic equilibrium with the ice Ih that
#' surrounds these pockets.  As the seaice temperature, t_seaice, may be 
#' less than the freezing temperature, SA_brine is usually greater than the
#' Absolute Salinity of the seawater at the time and place when and where 
#' the sea ice was formed.  So usually SA_brine will be larger than SA.  
#' The output, melting_seaice_SA_CT_ratio, is dSA/dCT rather than dCT/dSA. 
#' This is done so that when (SA - seaice_SA) = 0, the output, dSA/dCT is 
#' zero whereas dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#' @param sa_seaice Absolute Salinity of sea ice, that is, the mass fraction of salt in sea ice, expressed in g of salt per kg of sea ice. `[ g/kg ]`
#' @param t_seaice the in-situ temperature of the sea ice (or ice) (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_seaice_sa_ct_ratio()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_seaice_sa_ct_ratio.html)
#'
#' @export
gsw_melting_seaice_sa_ct_ratio <- function(sa, ct, p, sa_seaice, t_seaice) {
  recycled <- recycle_common(sa, ct, p, sa_seaice, t_seaice)
  .Call(teos10_c_gsw_melting_seaice_sa_ct_ratio_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]], recycled[[5]])
}

#' gsw_melting_seaice_sa_ct_ratio_poly
#'
#' Calculates the ratio of SA to CT changes when sea ice melts into seawater.
#' It is assumed that a small mass of sea ice melts into an infinite mass of
#' seawater.  Because of the infinite mass of seawater, the sea ice will
#' always melt.
#' Ice formed at the sea surface (sea ice) typically contains between 2 g/kg
#' and 12 g/kg of salt (defined as the mass of salt divided by the mass of
#' ice Ih plus brine) and this programme returns NaN's if the input
#' SA_seaice is greater than 15 g/kg.  If the SA_seaice input is not zero,
#' usually this would imply that the pressure p should be zero, as sea ice
#' only occurs near the sea surface.  The code does not impose that p = 0 if
#' SA_seaice is non-zero.  Rather, this is left to the user.
#' The Absolute Salinity, SA_brine, of the brine trapped in little pockets
#' in the sea ice, is in thermodynamic equilibrium with the ice Ih that
#' surrounds these pockets.  As the seaice temperature, t_seaice, may be
#' less than the freezing temperature, SA_brine is usually greater than the
#' Absolute Salinity of the seawater at the time and place when and where
#' the sea ice was formed.  So usually SA_brine will be larger than SA.
#' The output, melting_seaice_SA_CT_ratio, is dSA/dCT rather than dCT/dSA.
#' This is done so that when (SA - seaice_SA) = 0, the output, dSA/dCT is
#' zero whereas dCT/dSA would be infinite.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#' @param sa_seaice Absolute Salinity of sea ice, that is, the mass fraction of salt in sea ice, expressed in g of salt per kg of sea ice. `[ g/kg ]`
#' @param t_seaice the in-situ temperature of the sea ice (or ice) (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_melting_seaice_sa_ct_ratio_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_melting_seaice_sa_ct_ratio_poly.html)
#'
#' @export
gsw_melting_seaice_sa_ct_ratio_poly <- function(sa, ct, p, sa_seaice, t_seaice) {
  recycled <- recycle_common(sa, ct, p, sa_seaice, t_seaice)
  .Call(teos10_c_gsw_melting_seaice_sa_ct_ratio_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]], recycled[[5]])
}

#' gsw_p_from_z
#'
#' Calculates the pressure p from height z
#'
#' @param z height `[ m ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_p_from_z()`](http://www.teos-10.org/pubs/gsw/html/gsw_p_from_z.html)
#'
#' @export
gsw_p_from_z <- function(z, lat) {
  recycled <- recycle_common(z, lat)
  .Call(teos10_c_gsw_p_from_z_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_pot_enthalpy_from_pt_ice
#'
#' Calculates the potential enthalpy of ice from potential temperature of
#' ice (whose reference sea pressure is zero dbar).
#'
#' @param pt0_ice potential temperature of ice (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pot_enthalpy_from_pt_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_pot_enthalpy_from_pt_ice.html)
#'
#' @export
gsw_pot_enthalpy_from_pt_ice <- function(pt0_ice) {
  recycled <- recycle_common(pt0_ice)
  .Call(teos10_c_gsw_pot_enthalpy_from_pt_ice_wrap, recycled[[1]])
}

#' gsw_pot_enthalpy_from_pt_ice_poly
#'
#' Calculates the potential enthalpy of ice from potential temperature of
#' ice (whose reference sea pressure is zero dbar).  This is a
#' compuationally efficient polynomial fit to the potential enthalpy of
#' ice.
#'
#' @param pt0_ice potential temperature of ice (ITS-90) `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pot_enthalpy_from_pt_ice_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_pot_enthalpy_from_pt_ice_poly.html)
#'
#' @export
gsw_pot_enthalpy_from_pt_ice_poly <- function(pt0_ice) {
  recycled <- recycle_common(pt0_ice)
  .Call(teos10_c_gsw_pot_enthalpy_from_pt_ice_poly_wrap, recycled[[1]])
}

#' gsw_pot_enthalpy_ice_freezing
#'
#' Calculates the potential enthalpy of ice at which seawater freezes.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pot_enthalpy_ice_freezing()`](http://www.teos-10.org/pubs/gsw/html/gsw_pot_enthalpy_ice_freezing.html)
#'
#' @export
gsw_pot_enthalpy_ice_freezing <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_pot_enthalpy_ice_freezing_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_pot_enthalpy_ice_freezing_poly
#'
#' Calculates the potential enthalpy of ice at which seawater freezes.
#' The error of this fit ranges between -2.5 and 1 J/kg with an rms of 
#' 1.07, between SA of 0 and 120 g/kg and p between 0 and 10,000 dbar (the
#' error in the fit is between -0.7 and 0.7 with an rms of
#' 0.3, between SA of 0 and 120 g/kg and p between 0 and 5,000 dbar) when
#' compared with the potential enthalpy calculated from the exact in-situ 
#' freezing temperature which is found by a Newton-Raphson iteration of the 
#' equality of the chemical potentials of water in seawater and in ice.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pot_enthalpy_ice_freezing_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_pot_enthalpy_ice_freezing_poly.html)
#'
#' @export
gsw_pot_enthalpy_ice_freezing_poly <- function(sa, p) {
  recycled <- recycle_common(sa, p)
  .Call(teos10_c_gsw_pot_enthalpy_ice_freezing_poly_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_pot_rho_t_exact
#'
#' Calculates the potential density of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#' @param p_ref reference sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pot_rho_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_pot_rho_t_exact.html)
#'
#' @export
gsw_pot_rho_t_exact <- function(sa, t, p, p_ref) {
  recycled <- recycle_common(sa, t, p, p_ref)
  .Call(teos10_c_gsw_pot_rho_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_pressure_coefficient_ice
#'
#' Calculates pressure coefficient of ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pressure_coefficient_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_pressure_coefficient_ice.html)
#'
#' @export
gsw_pressure_coefficient_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_pressure_coefficient_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_pressure_freezing_ct
#'
#' Calculates the pressure (in dbar) of seawater at the freezing
#' temperature.  That is, the output is the pressure at which seawater,
#' with Absolute Salinity SA, Conservative Temperature CT, and with
#' saturation_fraction of dissolved air, freezes.  If the input values are
#' such that there is no value of pressure in the range between 0 dbar and
#' 10,000 dbar for which seawater is at the freezing temperature, the
#' output, pressure_freezing, is put equal to NaN.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pressure_freezing_ct()`](http://www.teos-10.org/pubs/gsw/html/gsw_pressure_freezing_ct.html)
#'
#' @export
gsw_pressure_freezing_ct <- function(sa, ct, saturation_fraction) {
  recycled <- recycle_common(sa, ct, saturation_fraction)
  .Call(teos10_c_gsw_pressure_freezing_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_pt_from_ct
#'
#' potential temperature of seawater from conservative temperature
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt_from_ct()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_ct.html)
#'
#' @export
gsw_pt_from_ct <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_pt_from_ct_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_pt_from_entropy
#'
#' Calculates potential temperature with reference pressure p_ref = 0 dbar 
#' and with entropy as an input variable.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param entropy specific entropy `[ deg C ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt_from_entropy()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_entropy.html)
#'
#' @export
gsw_pt_from_entropy <- function(sa, entropy) {
  recycled <- recycle_common(sa, entropy)
  .Call(teos10_c_gsw_pt_from_entropy_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_pt_from_pot_enthalpy_ice
#'
#' Calculates the potential temperature of ice from the potential enthalpy
#' of ice.  The reference sea pressure of both the potential temperature
#' and the potential enthalpy is zero dbar.
#'
#' @param pot_enthalpy_ice potential enthalpy of ice `[ J/kg ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt_from_pot_enthalpy_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_pot_enthalpy_ice.html)
#'
#' @export
gsw_pt_from_pot_enthalpy_ice <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt_from_pot_enthalpy_ice_wrap, recycled[[1]])
}

#' gsw_pt_from_pot_enthalpy_ice_poly
#'
#' Calculates the potential temperature of ice (whose reference sea 
#' pressure is zero dbar) from the potential enthalpy of ice.  This is a
#' compuationally efficient polynomial fit to the potential enthalpy of
#' ice.
#'
#' @param pot_enthalpy_ice potential enthalpy of ice `[ J/kg ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt_from_pot_enthalpy_ice_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_pot_enthalpy_ice_poly.html)
#'
#' @export
gsw_pt_from_pot_enthalpy_ice_poly <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt_from_pot_enthalpy_ice_poly_wrap, recycled[[1]])
}

#' gsw_pt_from_pot_enthalpy_ice_poly_dh
#'
#' Calculates the derivative of potential temperature of ice with respect 
#' to potential enthalpy.  This is based on the compuationally-efficient 
#' polynomial fit to the potential enthalpy of ice.
#'
#' @param pot_enthalpy_ice potential enthalpy of ice `[ J/kg ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt_from_pot_enthalpy_ice_poly_dh()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_pot_enthalpy_ice_poly_dh.html)
#'
#' @export
gsw_pt_from_pot_enthalpy_ice_poly_dh <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt_from_pot_enthalpy_ice_poly_dh_wrap, recycled[[1]])
}

#' gsw_pt_from_t
#'
#' Calculates potential temperature of seawater from in-situ temperature
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#' @param p_ref reference sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt_from_t()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_t.html)
#'
#' @export
gsw_pt_from_t <- function(sa, t, p, p_ref) {
  recycled <- recycle_common(sa, t, p, p_ref)
  .Call(teos10_c_gsw_pt_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_pt_from_t_ice
#'
#' Calculates potential temperature of ice Ih with the general reference
#' pressure, p_ref, from in-situ temperature, t.
#' A faster gsw routine exists if p_ref is indeed zero dbar.  This routine
#' is "gsw_pt0_from_t_ice(t,p)".
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#' @param p_ref reference sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt_from_t_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt_from_t_ice.html)
#'
#' @export
gsw_pt_from_t_ice <- function(t, p, p_ref) {
  recycled <- recycle_common(t, p, p_ref)
  .Call(teos10_c_gsw_pt_from_t_ice_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_pt0_cold_ice_poly
#'
#' Calculates an initial estimate of pt0_ice when it is less than about
#' -100 deg C.
#'
#' @param pot_enthalpy_ice potential enthalpy of ice `[ J/kg ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt0_cold_ice_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt0_cold_ice_poly.html)
#'
#' @export
gsw_pt0_cold_ice_poly <- function(pot_enthalpy_ice) {
  recycled <- recycle_common(pot_enthalpy_ice)
  .Call(teos10_c_gsw_pt0_cold_ice_poly_wrap, recycled[[1]])
}

#' gsw_pt0_from_t
#'
#' Calculates potential temperature with reference pressure, p_ref = 0 dbar.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt0_from_t()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt0_from_t.html)
#'
#' @export
gsw_pt0_from_t <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_pt0_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_pt0_from_t_ice
#'
#' Calculates potential temperature of ice Ih with a reference pressure of
#' 0 dbar, from in-situ temperature, t.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_pt0_from_t_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_pt0_from_t_ice.html)
#'
#' @export
gsw_pt0_from_t_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_pt0_from_t_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_rho
#'
#' Calculates in-situ density from Absolute Salinity and Conservative 
#' Temperature, using the computationally-efficient expression for
#' specific volume in terms of SA, CT and p (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_rho()`](http://www.teos-10.org/pubs/gsw/html/gsw_rho.html)
#'
#' @export
gsw_rho <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_rho_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_rho_ice
#'
#' Calculates in-situ density of ice from in-situ temperature and pressure.
#' Note that the output, rho_ice, is density, not density anomaly;  that 
#' is, 1000 kg/m^3 is not subracted from it.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_rho_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_rho_ice.html)
#'
#' @export
gsw_rho_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_rho_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_rho_t_exact
#'
#' Calculates in-situ density of seawater from Absolute Salinity and 
#' in-situ temperature.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_rho_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_rho_t_exact.html)
#'
#' @export
gsw_rho_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_rho_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sa_freezing_from_ct
#'
#' Calculates the Absolute Salinity of seawater at the freezing temperature.  
#' That is, the output is the Absolute Salinity of seawater, with 
#' Conservative Temperature CT, pressure p and the fraction 
#' saturation_fraction of dissolved air, that is in equilibrium 
#' with ice at the same in situ temperature and pressure.  If the input 
#' values are such that there is no positive value of Absolute Salinity for
#' which seawater is frozen, the output is made a NaN.
#'
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_freezing_from_ct()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_freezing_from_ct.html)
#'
#' @export
gsw_sa_freezing_from_ct <- function(ct, p, saturation_fraction) {
  recycled <- recycle_common(ct, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sa_freezing_from_ct_poly
#'
#' Calculates the Absolute Salinity of seawater at the freezing temperature.  
#' That is, the output is the Absolute Salinity of seawater, with the 
#' fraction saturation_fraction of dissolved air, that is in equilibrium 
#' with ice at Conservative Temperature CT and pressure p.  If the input 
#' values are such that there is no positive value of Absolute Salinity for
#' which seawater is frozen, the output is put equal to Nan.
#'
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_freezing_from_ct_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_freezing_from_ct_poly.html)
#'
#' @export
gsw_sa_freezing_from_ct_poly <- function(ct, p, saturation_fraction) {
  recycled <- recycle_common(ct, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_ct_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sa_freezing_from_t
#'
#' Calculates the Absolute Salinity of seawater at the freezing temperature.
#' That is, the output is the Absolute Salinity of seawater, with the
#' fraction saturation_fraction of dissolved air, that is in equilibrium
#' with ice at in-situ temperature t and pressure p.  If the input values
#' are such that there is no positive value of Absolute Salinity for which
#' seawater is frozen, the output is set to NaN.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_freezing_from_t()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_freezing_from_t.html)
#'
#' @export
gsw_sa_freezing_from_t <- function(t, p, saturation_fraction) {
  recycled <- recycle_common(t, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_t_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sa_freezing_from_t_poly
#'
#' Calculates the Absolute Salinity of seawater at the freezing temperature.
#' That is, the output is the Absolute Salinity of seawater, with the
#' fraction saturation_fraction of dissolved air, that is in equilibrium
#' with ice at in-situ temperature t and pressure p.  If the input values
#' are such that there is no positive value of Absolute Salinity for which
#' seawater is frozen, the output is put equal to Nan.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_freezing_from_t_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_freezing_from_t_poly.html)
#'
#' @export
gsw_sa_freezing_from_t_poly <- function(t, p, saturation_fraction) {
  recycled <- recycle_common(t, p, saturation_fraction)
  .Call(teos10_c_gsw_sa_freezing_from_t_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sa_from_rho
#'
#' Calculates the Absolute Salinity of a seawater sample, for given values
#' of its density, Conservative Temperature and sea pressure (in dbar).
#'
#' @param rho in-situ density	`[ kg/m ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_from_rho()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_from_rho.html)
#'
#' @export
gsw_sa_from_rho <- function(rho, ct, p) {
  recycled <- recycle_common(rho, ct, p)
  .Call(teos10_c_gsw_sa_from_rho_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sa_from_sp
#'
#' Calculates Absolute Salinity, SA, from Practical Salinity, SP
#'
#' @param sp Practical Salinity `[ unitless ]`
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_from_sp()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_from_sp.html)
#'
#' @export
gsw_sa_from_sp <- function(sp, p, lon, lat) {
  recycled <- recycle_common(sp, p, lon, lat)
  .Call(teos10_c_gsw_sa_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_sa_from_sp_baltic
#'
#' For the Baltic Sea, calculates Absolute Salinity with a value
#' computed analytically from Practical Salinity
#'
#' @param sp Practical Salinity `[ unitless ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_from_sp_baltic()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_from_sp_baltic.html)
#'
#' @export
gsw_sa_from_sp_baltic <- function(sp, lon, lat) {
  recycled <- recycle_common(sp, lon, lat)
  .Call(teos10_c_gsw_sa_from_sp_baltic_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sa_from_sstar
#'
#' Calculates Absolute Salinity, SA, from Preformed Salinity, Sstar.
#'
#' @param sstar Preformed Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sa_from_sstar()`](http://www.teos-10.org/pubs/gsw/html/gsw_sa_from_sstar.html)
#'
#' @export
gsw_sa_from_sstar <- function(sstar, p, lon, lat) {
  recycled <- recycle_common(sstar, p, lon, lat)
  .Call(teos10_c_gsw_sa_from_sstar_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_saar
#'
#' function gsw_saar(p,long,lat)
#' !==========================================================================
#' 
#' Calculates the Absolute Salinity Anomaly Ratio, SAAR at a geographic point.
#'
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_saar()`](http://www.teos-10.org/pubs/gsw/html/gsw_saar.html)
#'
#' @export
gsw_saar <- function(p, lon, lat) {
  recycled <- recycle_common(p, lon, lat)
  .Call(teos10_c_gsw_saar_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sigma0
#'
#' Calculates potential density anomaly with reference pressure of 0 dbar,
#' this being this particular potential density minus 1000 kg/m^3.  This
#' function has inputs of Absolute Salinity and Conservative Temperature.
#' This function uses the computationally-efficient 48-term expression for 
#' density in terms of SA, CT and p (IOC et al., 2010).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sigma0()`](http://www.teos-10.org/pubs/gsw/html/gsw_sigma0.html)
#'
#' @export
gsw_sigma0 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma0_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_sigma1
#'
#' Calculates potential density anomaly with reference pressure of 1000 dbar,
#' this being this particular potential density minus 1000 kg/m^3.  This
#' function has inputs of Absolute Salinity and Conservative Temperature.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sigma1()`](http://www.teos-10.org/pubs/gsw/html/gsw_sigma1.html)
#'
#' @export
gsw_sigma1 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma1_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_sigma2
#'
#' Calculates potential density anomaly with reference pressure of 2000 dbar,
#' this being this particular potential density minus 1000 kg/m^3.  This
#' function has inputs of Absolute Salinity and Conservative Temperature.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sigma2()`](http://www.teos-10.org/pubs/gsw/html/gsw_sigma2.html)
#'
#' @export
gsw_sigma2 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma2_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_sigma3
#'
#' Calculates potential density anomaly with reference pressure of 3000 dbar,
#' this being this particular potential density minus 1000 kg/m^3.  This
#' function has inputs of Absolute Salinity and Conservative Temperature.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sigma3()`](http://www.teos-10.org/pubs/gsw/html/gsw_sigma3.html)
#'
#' @export
gsw_sigma3 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma3_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_sigma4
#'
#' Calculates potential density anomaly with reference pressure of 4000 dbar,
#' this being this particular potential density minus 1000 kg/m^3.  This
#' function has inputs of Absolute Salinity and Conservative Temperature.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sigma4()`](http://www.teos-10.org/pubs/gsw/html/gsw_sigma4.html)
#'
#' @export
gsw_sigma4 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_sigma4_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_sound_speed
#'
#' Calculates the speed of sound in seawater.  This function has inputs of
#' Absolute Salinity and Conservative Temperature.  This function uses the
#' computationally-efficient expression for specific volume in terms of SA,
#' CT and p (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sound_speed()`](http://www.teos-10.org/pubs/gsw/html/gsw_sound_speed.html)
#'
#' @export
gsw_sound_speed <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_sound_speed_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sound_speed_ice
#'
#' Calculates the compression speed of sound in ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sound_speed_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_sound_speed_ice.html)
#'
#' @export
gsw_sound_speed_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_sound_speed_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_sound_speed_t_exact
#'
#' Calculates the speed of sound in seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sound_speed_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_sound_speed_t_exact.html)
#'
#' @export
gsw_sound_speed_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_sound_speed_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sp_from_c
#'
#' Calculates Practical Salinity, SP, from conductivity, C, primarily using
#' the PSS-78 algorithm.  Note that the PSS-78 algorithm for Practical
#' Salinity is only valid in the range 2 < SP < 42.  If the PSS-78
#' algorithm produces a Practical Salinity that is less than 2 then the
#' Practical Salinity is recalculated with a modified form of the Hill et
#' al. (1986) formula.  The modification of the Hill et al. (1986)
#' expression is to ensure that it is exactly consistent with PSS-78
#' at SP = 2.  Note that the input values of conductivity need to be in
#' units of mS/cm (not S/m).
#'
#' @param c conductivity `[ mS/cm ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sp_from_c()`](http://www.teos-10.org/pubs/gsw/html/gsw_sp_from_c.html)
#'
#' @export
gsw_sp_from_c <- function(c, t, p) {
  recycled <- recycle_common(c, t, p)
  .Call(teos10_c_gsw_sp_from_c_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sp_from_sa
#'
#' Calculates Practical salinity, sp, from Absolute salinity, sa
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sp_from_sa()`](http://www.teos-10.org/pubs/gsw/html/gsw_sp_from_sa.html)
#'
#' @export
gsw_sp_from_sa <- function(sa, p, lon, lat) {
  recycled <- recycle_common(sa, p, lon, lat)
  .Call(teos10_c_gsw_sp_from_sa_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_sp_from_sa_baltic
#'
#' For the Baltic Sea, calculates Practical Salinity with a value
#' computed analytically from Absolute Salinity
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sp_from_sa_baltic()`](http://www.teos-10.org/pubs/gsw/html/gsw_sp_from_sa_baltic.html)
#'
#' @export
gsw_sp_from_sa_baltic <- function(sa, lon, lat) {
  recycled <- recycle_common(sa, lon, lat)
  .Call(teos10_c_gsw_sp_from_sa_baltic_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_sp_from_sk
#'
#' Calculates Practical Salinity, SP, from SK
#'
#' @param sk Knudsen Salinity `[ parts per thousand, ppt ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sp_from_sk()`](http://www.teos-10.org/pubs/gsw/html/gsw_sp_from_sk.html)
#'
#' @export
gsw_sp_from_sk <- function(sk) {
  recycled <- recycle_common(sk)
  .Call(teos10_c_gsw_sp_from_sk_wrap, recycled[[1]])
}

#' gsw_sp_from_sr
#'
#' Calculates Practical Salinity, sp, from Reference Salinity, sr.
#'
#' @param sr Reference Salinity `[ g/kg ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sp_from_sr()`](http://www.teos-10.org/pubs/gsw/html/gsw_sp_from_sr.html)
#'
#' @export
gsw_sp_from_sr <- function(sr) {
  recycled <- recycle_common(sr)
  .Call(teos10_c_gsw_sp_from_sr_wrap, recycled[[1]])
}

#' gsw_sp_from_sstar
#'
#' Calculates Practical Salinity, SP, from Preformed Salinity, Sstar.
#'
#' @param sstar Preformed Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sp_from_sstar()`](http://www.teos-10.org/pubs/gsw/html/gsw_sp_from_sstar.html)
#'
#' @export
gsw_sp_from_sstar <- function(sstar, p, lon, lat) {
  recycled <- recycle_common(sstar, p, lon, lat)
  .Call(teos10_c_gsw_sp_from_sstar_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_specvol
#'
#' Calculates specific volume from Absolute Salinity, Conservative
#' Temperature and pressure, using the computationally-efficient
#' polynomial expression for specific volume (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_specvol()`](http://www.teos-10.org/pubs/gsw/html/gsw_specvol.html)
#'
#' @export
gsw_specvol <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_specvol_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_specvol_anom_standard
#'
#' Calculates specific volume anomaly of seawater.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_specvol_anom_standard()`](http://www.teos-10.org/pubs/gsw/html/gsw_specvol_anom_standard.html)
#'
#' @export
gsw_specvol_anom_standard <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_specvol_anom_standard_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_specvol_ice
#'
#' Calculates the specific volume of ice.
#'
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_specvol_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_specvol_ice.html)
#'
#' @export
gsw_specvol_ice <- function(t, p) {
  recycled <- recycle_common(t, p)
  .Call(teos10_c_gsw_specvol_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_specvol_sso_0
#'
#' This function calculates specific volume at the Standard Ocean Salinty,
#' SSO, and at a Conservative Temperature of zero degrees C, as a function 
#' of pressure, p, in dbar, using a streamlined version of the CT version
#' of specific volume, that is, a streamlined version of the code
#' "gsw_specvol(SA,CT,p)".
#'
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_specvol_sso_0()`](http://www.teos-10.org/pubs/gsw/html/gsw_specvol_sso_0.html)
#'
#' @export
gsw_specvol_sso_0 <- function(p) {
  recycled <- recycle_common(p)
  .Call(teos10_c_gsw_specvol_sso_0_wrap, recycled[[1]])
}

#' gsw_specvol_t_exact
#'
#' Calculates the specific volume of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_specvol_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_specvol_t_exact.html)
#'
#' @export
gsw_specvol_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_specvol_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_spiciness0
#'
#' Calculates spiciness from Absolute Salinity and Conservative 
#' Temperature at a pressure of 0 dbar, as described by McDougall and 
#' Krzysik (2015).  This routine is based on the computationally-efficient 
#' expression for specific volume in terms of SA, CT and p (Roquet et al., 
#' 2015).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_spiciness0()`](http://www.teos-10.org/pubs/gsw/html/gsw_spiciness0.html)
#'
#' @export
gsw_spiciness0 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_spiciness0_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_spiciness1
#'
#' Calculates spiciness from Absolute Salinity and Conservative 
#' Temperature at a pressure of 1000 dbar, as described by McDougall and 
#' Krzysik (2015).  This routine is based on the computationally-efficient 
#' expression for specific volume in terms of SA, CT and p (Roquet et al., 
#' 2015).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_spiciness1()`](http://www.teos-10.org/pubs/gsw/html/gsw_spiciness1.html)
#'
#' @export
gsw_spiciness1 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_spiciness1_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_spiciness2
#'
#' Calculates spiciness from Absolute Salinity and Conservative 
#' Temperature at a pressure of 2000 dbar, as described by McDougall and 
#' Krzysik (2015).  This routine is based on the computationally-efficient 
#' expression for specific volume in terms of SA, CT and p (Roquet et al., 
#' 2015).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_spiciness2()`](http://www.teos-10.org/pubs/gsw/html/gsw_spiciness2.html)
#'
#' @export
gsw_spiciness2 <- function(sa, ct) {
  recycled <- recycle_common(sa, ct)
  .Call(teos10_c_gsw_spiciness2_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_sr_from_sp
#'
#' Calculates Reference Salinity, SR, from Practical Salinity, SP.
#'
#' @param sp Practical Salinity `[ unitless ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sr_from_sp()`](http://www.teos-10.org/pubs/gsw/html/gsw_sr_from_sp.html)
#'
#' @export
gsw_sr_from_sp <- function(sp) {
  recycled <- recycle_common(sp)
  .Call(teos10_c_gsw_sr_from_sp_wrap, recycled[[1]])
}

#' gsw_sstar_from_sa
#'
#' Calculates Preformed Salinity, Sstar, from Absolute Salinity, SA.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sstar_from_sa()`](http://www.teos-10.org/pubs/gsw/html/gsw_sstar_from_sa.html)
#'
#' @export
gsw_sstar_from_sa <- function(sa, p, lon, lat) {
  recycled <- recycle_common(sa, p, lon, lat)
  .Call(teos10_c_gsw_sstar_from_sa_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_sstar_from_sp
#'
#' Calculates Preformed Salinity, Sstar, from Practical Salinity, SP.
#'
#' @param sp Practical Salinity `[ unitless ]`
#' @param p sea pressure `[ dbar ]`
#' @param lon longitude `[ deg E ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_sstar_from_sp()`](http://www.teos-10.org/pubs/gsw/html/gsw_sstar_from_sp.html)
#'
#' @export
gsw_sstar_from_sp <- function(sp, p, lon, lat) {
  recycled <- recycle_common(sp, p, lon, lat)
  .Call(teos10_c_gsw_sstar_from_sp_wrap, recycled[[1]], recycled[[2]], recycled[[3]], recycled[[4]])
}

#' gsw_t_deriv_chem_potential_water_t_exact
#'
#' Calculates the temperature derivative of the chemical potential of water
#' in seawater so that it is valid at exactly SA = 0.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param t in-situ temperature (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_t_deriv_chem_potential_water_t_exact()`](http://www.teos-10.org/pubs/gsw/html/gsw_t_deriv_chem_potential_water_t_exact.html)
#'
#' @export
gsw_t_deriv_chem_potential_water_t_exact <- function(sa, t, p) {
  recycled <- recycle_common(sa, t, p)
  .Call(teos10_c_gsw_t_deriv_chem_potential_water_t_exact_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_t_freezing
#'
#' Calculates the in-situ temperature at which seawater freezes
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_t_freezing()`](http://www.teos-10.org/pubs/gsw/html/gsw_t_freezing.html)
#'
#' @export
gsw_t_freezing <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_t_freezing_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_t_freezing_poly
#'
#' Calculates the in-situ temperature at which seawater freezes from a
#' computationally efficient polynomial.
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param p sea pressure `[ dbar ]`
#' @param saturation_fraction the saturation fraction of dissolved air in seawater
#'
#' @seealso [Official TEOS-10 documentation for `gsw_t_freezing_poly()`](http://www.teos-10.org/pubs/gsw/html/gsw_t_freezing_poly.html)
#'
#' @export
gsw_t_freezing_poly <- function(sa, p, saturation_fraction) {
  recycled <- recycle_common(sa, p, saturation_fraction)
  .Call(teos10_c_gsw_t_freezing_poly_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_t_from_ct
#'
#' Calculates in-situ temperature from Conservative Temperature of seawater
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_t_from_ct()`](http://www.teos-10.org/pubs/gsw/html/gsw_t_from_ct.html)
#'
#' @export
gsw_t_from_ct <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_t_from_ct_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_t_from_pt0_ice
#'
#' Calculates in-situ temperature from the potential temperature of ice Ih 
#' with reference pressure, p_ref, of 0 dbar (the surface), and the 
#' in-situ pressure.
#'
#' @param pt0_ice potential temperature of ice (ITS-90) `[ deg C ]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_t_from_pt0_ice()`](http://www.teos-10.org/pubs/gsw/html/gsw_t_from_pt0_ice.html)
#'
#' @export
gsw_t_from_pt0_ice <- function(pt0_ice, p) {
  recycled <- recycle_common(pt0_ice, p)
  .Call(teos10_c_gsw_t_from_pt0_ice_wrap, recycled[[1]], recycled[[2]])
}

#' gsw_thermobaric
#'
#' Calculates the thermobaric coefficient of seawater with respect to
#' Conservative Temperature.  This routine is based on the
#' computationally-efficient expression for specific volume in terms of
#' SA, CT and p (Roquet et al., 2014).
#'
#' @param sa Absolute Salinity `[ g/kg ]`
#' @param ct Conservative Temperature `[deg C]`
#' @param p sea pressure `[ dbar ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_thermobaric()`](http://www.teos-10.org/pubs/gsw/html/gsw_thermobaric.html)
#'
#' @export
gsw_thermobaric <- function(sa, ct, p) {
  recycled <- recycle_common(sa, ct, p)
  .Call(teos10_c_gsw_thermobaric_wrap, recycled[[1]], recycled[[2]], recycled[[3]])
}

#' gsw_z_from_p
#'
#' Calculates the height z from pressure p
#'
#' @param p sea pressure `[ dbar ]`
#' @param lat latitude `[ deg N ]`
#'
#' @seealso [Official TEOS-10 documentation for `gsw_z_from_p()`](http://www.teos-10.org/pubs/gsw/html/gsw_z_from_p.html)
#'
#' @export
gsw_z_from_p <- function(p, lat) {
  recycled <- recycle_common(p, lat)
  .Call(teos10_c_gsw_z_from_p_wrap, recycled[[1]], recycled[[2]])
}
